name: noclick_me
description: Share links with more descriptive URLs!

# Prevents the package from being accidentally published using `pub publish`.
publish_to: 'none'

version: 0.3.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  duration: ^3.0.6
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.1
  flutter_linkify: ^5.0.2
  flutter_screenutil: ^5.0.0
  flutter_svg: ^0.22.0
  http: ^0.13.2
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^2.0.2
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.9.0
  mockito: ^5.0.7
  pedantic: ^1.9.0
  plugin_platform_interface: ^2.0.0
  url_launcher_platform_interface: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/noclick.png
    - doc/legal/privacy.md
    - doc/sponsoring.md

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
